  version: '3.8'

  services:
    app:
      build:
        context: .
        dockerfile: Dockerfile
      image: gilanghuda/sobi-go-app:latest
      container_name: sobi_app
      ports:
        - "8000:8000"
      environment:
        DB_DOCKER_HOST: ${DB_DOCKER_HOST}
        DB_DOCKER_PORT: ${DB_DOCKER_PORT}
        DB_DOCKER_USER: ${DB_DOCKER_USER}
        DB_DOCKER_PASSWORD: ${DB_DOCKER_PASSWORD}
        DB_DOCKER_NAME: ${DB_DOCKER_NAME}
        JWT_SECRET: ${JWT_SECRET}
      depends_on:
        postgres:
          condition: service_healthy
      restart: unless-stopped
      networks:
        - sobi_net

    postgres:
      image: postgres:15
      container_name: sobi_postgres
      ports:
        - "5432:5432"
      volumes:
        - pg_data:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: ${DB_DOCKER_USER}
        POSTGRES_PASSWORD: ${DB_DOCKER_PASSWORD}
        POSTGRES_DB: ${DB_DOCKER_NAME}
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${DB_DOCKER_USER} -d ${DB_DOCKER_NAME}"]
        interval: 5s
        timeout: 5s
        retries: 5
      restart: unless-stopped
      networks:
        - sobi_net

  volumes:
    pg_data:

  networks:
    sobi_net:
      driver: bridge