name: Build and Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Export secrets to env
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> $GITHUB_ENV
          echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV
          echo "DB_DOCKER_HOST=${{ secrets.DB_DOCKER_HOST }}" >> $GITHUB_ENV
          echo "DB_DOCKER_PORT=${{ secrets.DB_DOCKER_PORT }}" >> $GITHUB_ENV
          echo "DB_DOCKER_USER=${{ secrets.DB_DOCKER_USER }}" >> $GITHUB_ENV
          echo "DB_DOCKER_PASSWORD=${{ secrets.DB_DOCKER_PASSWORD }}" >> $GITHUB_ENV
          echo "DB_DOCKER_NAME=${{ secrets.DB_DOCKER_NAME }}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sobi-go-app:latest

